In [0]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt
from numpy import array
from numpy import argmax
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

print(tf.__version__)

1.15.0


In [0]:
# Import tensorflow's MNIST data handle
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 8s 1us/step


*Label* to *integers* to *binaries*.

In [0]:
# define example
data = ['cold', 'cold','warm','cold','hot','hot','warm','cold','warm','hot']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [0]:
print(train_labels)
print(type(train_labels[0]))

#Le labels di MNIST sono salvate già come interi

[5 0 4 ... 5 6 8]
<class 'numpy.uint8'>


In [0]:
# one hot encode
one_hot_labels_train = to_categorical(train_labels)
print(one_hot_labels_train)
print("Controllo l'i-esimo valore: ")
i=25
print(train_labels[i])
print(one_hot_labels_train[i])
# invert encoding
inverted = argmax(one_hot_labels_train[i])
print(inverted)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
Controllo l'i-esimo valore: 
2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
2


**NB: Sia *train_labels* che *test_labels* devono essere one-hot encoded (o nessuna delle due).**

In [0]:
one_hot_labels_test = to_categorical(test_labels)
print("Controllo il j-esimo valore: ")
j = 37
print(test_labels[j])
print(argmax(one_hot_labels_test[j]))

Controllo il j-esimo valore: 
1
1
