#Test perdita di precisione

Testo se a seguito della divisione con 65535.0, fare il cast a float32 perde di precisione.

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [4]:
import numpy as np
from numpy import random
# Online Python compiler (interpreter) to run Python online.
# Write Python 3 code in this online editor and run it.

print("Hello world")


x=random.randint(65535, size=(10))
y = x
z = y
k = z

print(x)
print(y)
print(z)
print(k)

print("====")

x = x / 65535.0
print("Float")
print(x)

y = y / 65535.0
y = y.reshape(-1).astype(np.single)
print("Single")
print(y)

z = z / 65535.0
z = z.reshape(-1).astype(np.double)
print("Double")
print(z)


np.longdouble
k = k / 65535.0
k = k.reshape(-1).astype(np.longdouble)
print("Long double")
print(k)

Hello world
[39324  3352 31809 38582 34254 41288 19782 48436 25637 20484]
[39324  3352 31809 38582 34254 41288 19782 48436 25637 20484]
[39324  3352 31809 38582 34254 41288 19782 48436 25637 20484]
[39324  3352 31809 38582 34254 41288 19782 48436 25637 20484]
====
Float
[0.60004578 0.05114824 0.48537423 0.58872358 0.52268254 0.6300145
 0.30185397 0.73908598 0.39119554 0.3125658 ]
Single
[0.6000458  0.05114824 0.48537424 0.5887236  0.52268255 0.6300145
 0.30185398 0.739086   0.39119554 0.3125658 ]
Double
[0.60004578 0.05114824 0.48537423 0.58872358 0.52268254 0.6300145
 0.30185397 0.73908598 0.39119554 0.3125658 ]
Long double
[0.60004578 0.05114824 0.48537423 0.58872358 0.52268254 0.6300145
 0.30185397 0.73908598 0.39119554 0.3125658 ]
